### ISSUE TITLE
Extend push-version with option to override downstream git branch

### ISSUE THREAD

**Issue by robertgartman** [jenkins-x/updatebot#42]
**A feature request**

Extend `push-version` with an option that supports override of target branch names. Example `--target-branch=<branch-name>`. From the technical POV, the target-branch sets the value used as `base` input in https://developer.github.com/v3/pulls/#create-a-pull-request 

Rationale: assume a service having upstream library dependencies like this:

    Library: model
        |
        V
    Library: make
        |
        V
    Service: cars

There are situations when a new features hit all of the code above, creating non-backwards compatibility. The standard tool in the toolbox is git branching.

**Issue**

As of today there is no suppoprt in Updatebot to push a version change to a downstream base branch other than master. The code indicates a possibility to configure another branch in the .updatebot YAML file but even so, it will not fly. We need to set it dynamically.

Example:

A change in  `Library: model` inside branch `feature-dropfossilfuel` will create a PR to `Library: make`, which will have _master_ as the "base" branch. Consequences:

- There is no clear path to make  `Service: cars` dependant on the PR in `Library: make`.
- Accepting the PR in `Library: make` will merge changes into master. This will "pollute" the master with the breaking change and there is still no clear path on how to push this downstream to branch `feature-dropfossilfuel` of `Service: cars`

**Proposed solution**

With a flag such as `--target-branch=<branch-name>` we can put code like this (Java Maven example) in the build step for the libraries:

    sh "jx step git credentials"
    sh "echo \$(jx-release-version)-$BRANCH_NAME > VERSION"
    sh "mvn clean versions:set -DnewVersion=\$(cat VERSION)"
    sh "mvn deploy"
    sh "git commit -a -m \"feature \$(cat VERSION)\""
    sh "git tag -fa v\$(cat VERSION) -m \"feature version \$(cat VERSION)\""
    sh "git push origin v\$(cat VERSION)"

    sh 'updatebot push-version --kind maven --target-branch=\$BRANCH_NAME com.example:model \$(cat VERSION)'

We simply assume that if the library is within a feature branch then it WILL push changes to a downstream repo with the same feature name. We'll then end up with this build flow (assuming changes in Library: model):

    Library: model (feature-dropfossilfuel)
        |
        | artifact com.example:model:1.2.3-feature-dropfossilfuel -> Nexus
        V
    Library: make (PR against feature-dropfossilfuel)
        |
        | Accept PR via update-loop in bild job of Library: model
        V
    Library: make (feature-dropfossilfuel, referencing com.example:model:1.2.3-feature-dropfossilfuel)
        |
        | artifact com.example:make:4.12.7-feature-dropfossilfuel -> Nexus
        V
    Service: cars (PR against feature-dropfossilfuel, referencing com.example:model:1.2.3-feature-dropfossilfuel)
        |
        | Accept PR via update-loop in bild job of Library: make
        V
    Service: cars (feature-dropfossilfuel, referencing com.example:make:4.12.7-feature-dropfossilfuel)

**Bonus feature 1**

Would be great if Updatebot creates the branch in the downstream repo if not already present. The alternative is some informative failure message.

**Bonus feature 2**

When working in a feature there can be considerable gains in build time and resources by skipping the Pull Request step and merge with downstream feature branch right away. The PR approach makes a lot of sense when using the master branch as base. But for development of libraries in a feature we're quite happy trading the GitOps flow for build speed. Let's assume the flag `--skip-pr=true`. We can then apply this when building libraries:

    sh 'updatebot push-version --kind maven --skip-pr=true --target-branch=\$BRANCH_NAME com.example:model \$(cat VERSION)'

The resulting build flow (assuming changes in model):

    Library: model (feature-dropfossilfuel)
        |
        | artifact com.example:model:1.2.3-feature-dropfossilfuel -> Nexus
        V
    Library: make (feature-dropfossilfuel, referencing com.example:model:1.2.3-feature-dropfossilfuel)
        |
        | artifact com.example:make:4.12.7-feature-dropfossilfuel -> Nexus
        V
    Service: cars (feature-dropfossilfuel, referencing com.example:make:4.12.7-feature-dropfossilfuel)

And... if you already have a nifty solution to the issue above - please spread some lights to us in the dark!

**Comment by ryandawsonuk** [comment]
FWIW, the updatebot was indeed recently extended to allow different branches to be specified in the .updatebot.yml file (https://github.com/jenkins-x/updatebot/pull/39/files)

Since you seem to want to apply the same branch to all of the downstream repos in the .yml file, I guess you're looking for a way to override the .yml file. I think that could be implemented by adding an optional (i..e. do a null check) override parameter to https://github.com/jenkins-x/updatebot/blob/b6d3dbe6b54db6a53c118e3d406ee42e2ddf6499/updatebot-core/src/main/java/io/jenkins/updatebot/repository/LocalRepository.java#L192 and passing that in from the places that call it. I think ModifyFilesCommandSupport would need to be extended to take an extra parameter (in the way that PushSourceChanges does, which extends it). Then I think the same would need to be done with cloneOrPullRepositories and cloneOrPullRepository in Repositories. The Repositories class is called directly from CommandSupport, which also has access to parameters but seems to get to them in a different way.

Or a workaround for you might be to simply do an automated find-replace of the branch-name in the .updatebot.yml file before you run `push-version`
